FROM nginx
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY aptitudeguruhem.crt /etc/ssl/certs/aptitudeguruhem.crt
COPY aptitudeguruhem.key /etc/ssl/private/aptitudeguruhem.key
