version: '3'

services:
  express-server:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 3  # Set the number of replicas as needed
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 120s 
    ports:
      - "3000"
    

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - express-server
